services:
  rbs-backend:
    restart: always
    environment:
      NODE_ENV: production

  postgres:
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    # Add memory limit for Postgres
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 1G
          cpus: '1'

volumes:
  postgres_prod_data:
    external: true
