name: Deploy to Production

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS

    steps:
      - name: Set up SSH agent & Run Deploy CI script
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST_2 }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY_2 }}
          script: |
            echo "SSH setup completed."
            cd apps/rbs-travels-backend-express
            git pull 
            ./deploy-ci.sh
            echo "Github Actions Done in Deployment"
